services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: Karma
      MYSQL_ROOT_PASSWORD : karma
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "5000:3306"
    volumes:
      - ./BackupDB.sql:/docker-entrypoint-initdb.d/BackupDB.sql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db        
      PMA_PORT: 3306      
    ports:
      - "8080:80"
    depends_on:
      - db
  
  # Backend:
  #   dockerfile : Dockerfile
  #   container_name: Backend-services
  #   environment:
  #     - DATABASE_URL=mysql://root:karma@db:3306